name: Run clang-format Linter

on:
  push:
    branches:
      - main
      - dev
      - issue-128-test
  pull_request_target:
    branches:
      - main
      - dev
      - issue-128-test
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
      # format the latest commit
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v28.0.0
        with:
          files: |
            src/Features/*.cpp
            src/Features/*.h
            **/*.hlsl
            **/*.hlsli
          separator: ","
      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
          export CHANGED_FILES

          IFS=$',' read -a MODIFIED_FILES_ARRAY <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          for file in "${MODIFIED_FILES_ARRAY[@]}"; do
            echo $file
            CHANGED_FILES+=\"
            CHANGED_FILES+="$file"
            CHANGED_FILES+=\"
            CHANGED_FILES+=' '
          done
          CHANGED_FILES="${CHANGED_FILES//\"/'%22'}"
          unset IFS

          echo "my_changed_files=$CHANGED_FILES" >> "$GITHUB_ENV"
          echo $CHANGED_FILES > modified_files.txt
          echo "::set-outputs name=all_changed_files::$CHANGED_FILES"
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          echo "${{env.my_changed_files}}"

      - name: test
        run: |
          echo "${{steps.changed-files.outputs.all_changed_files}}"
      - name: Format changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          changedFiles: ${{env.my_changed_files}}
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          # source: ${{env.my_changed_files}}
          # source: ${{changedFiles}}
          # source: ARGS
          # source: $CHANGED_FILES
          exclude: "extern include"
          extensions: "h,cpp,c,hlsl,hlsli"
          clangFormatVersion: 16
          inplace: True # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: 🎨 apply clang-format changes"
          branch: ${{ github.head_ref }}
