name: Run clang-format Linter

on:
  push:
    branches:
      - main
      - dev
      - rjwignar/issue-128-test
  pull_request_target:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
      # format the latest commit
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v42.0.5
        with:
          files: |
            src/Features/*.cpp
            src/Features/*.h
            **/*.hlsl
            **/*.hlsli
            separator: ","
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Process list of changed files
        id: process-list
        run: |
          CHANGED_FILES=(${{ steps.changed-files.outputs.all_changed_files }})
          CHANGED_FILES="${CHANGED_FILES// /\\ }"
          CHANGED_FILES="${CHANGED_FILES//, / }"
          echo $CHANGED_FILES
          echo "::set-outputs name=changed_files::${CHANGED_FILES}"
      - name: Format changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "${{ steps.process-list.outputs.changed_files }}"
          exclude: "extern include"
          extensions: "h,cpp,c,hlsl,hlsli"
          clangFormatVersion: 16
          inplace: True # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: 🎨 apply clang-format changes"
          branch: ${{ github.head_ref }}
